name: main
on: push
jobs:
  some-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run setup
        run: make setup

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
